# Generated by Django 5.2.4 on 2025-08-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('video', 'user')},
        ),
    ]
